services:
  frontjs:
    build:
      context: ./battlegames-front/
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:8080'
    depends_on: [nodejs]
  nodejs:
    build:
      context: ./battlegames-back/
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_HOST=mongo
      - PORT=3000
    ports:
      - '3000:3000'
    depends_on: [mongo]
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: {}